{% set version = '1.1.1' %}
{% set build_number = '1' %}
{% set action = action or 'release' %}
{% set py = _python | replace('*', '') | replace(' ', '') | replace('.', '') %}
{% set test_requirements = action in ["test", "coverage", "benchmark"] %}

package:
  name: pyeantic
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: py{{ py }}_{{ build_number }}
  # e-antic & cppyy are not available for Windows, https://github.com/conda-forge/e-antic-feedstock/issues/6
  skip: True  # [win]
  # e-antic is not available on macOS, https://github.com/flatsurf/e-antic-feedstock/pull/3
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage("pyeantic", max_pin="x") }}

requirements:
  build:
    - libtool
    - automake
    # to search for the renfxx library, the C++ wrapper for e-antic
    - {{ compiler('cxx') }}
  host:
    - python {{ _python }}
    - setuptools
    # configure is looking for all the runtime dependencies during the build
    - cppyy
    - boost-cpp
    - e-antic >=1.0a master_1110
{%- if test_requirements %}
    # enable check-valgrind in ./configure
    - valgrind >=3.15.0  # [linux]
    # We use pytest for testing
    - pytest
    # We want to run our optional SageMath tests
    - sagelib
    - pip
    - ipywidgets
    - sympy
{%- endif %}
  run:
    - python {{ _python }}
    - cppyy
    - boost-cpp

{%- if action == "release" %}
test:
  imports:
    - pyeantic
{%- endif %}

about:
  home: https://github.com/flatsurf/pyeantic
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: Python Wrapper for E-ANTIC

extra:
  recipe-maintainers:
    - saraedum
    - videlec
  variables:
    job: {{ job }}
    action: {{ action }}
