# conda-smithy assumes that the build number is >= 1000 when building with the new anaconda compilers,
# this probably is not important but make_build_number otherwise complains during the build
# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = (environ.get('GIT_DESCRIBE_NUMBER')|int + 1000)|string %}
{% set build_string = "master_" + build_number %}
{% set flavour = environ.get('FLAVOUR', 'build')|string %}

package:
  name: pyeantic
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ build_string }}
  # eantic is not available for Windows
  skip: True  # [win]
  # this is a pure Python package (though it depends on non-Python libraries through cppyy)
  noarch: python
  script:
    - ./recipe/build-{{ flavour }}.sh
    # conda-build can currently not copy build-artifacts over to the testing
    # stage, so we can only run make check if we rebuild everything. Therefore,
    # we run make check as part of the build in the usual make; make check;
    # make install order.
    - ./recipe/test-{{ flavour }}.sh
    - make install

requirements:
  build:
    - libtool
    - automake
    # to search for the renfxx library, the C++ wrapper for e-antic
    - {{ compiler('cxx') }}
  host:
    - python >=3.6
    - setuptools
    # We need all runtime dependencies to run tests during the build
    - cppyy
    - boost-cpp
    - e-antic 1.*
    # We use pytest for testing
    - pytest
    # We want to run our optional SageMath tests
    - sage
    # We need pip so SageMath's installed_packages() works, see https://github.com/conda-forge/sage-feedstock/pull/46
    - pip
  run:
    - cppyy
    - boost-cpp
    # Strangely run_exports of e-antic is not picked up correctly (it's missing from the package on flatsurf)
    # This is probably due to recent bugs in conda-build (mid 2019)
    - e-antic 1.*
  run_exports:
    - pyeantic {{ version }}

test:
  imports:
    - pyeantic

about:
  home: https://github.com/flatsurf/pyeantic
  license: GPL3
  license_file: COPYING
  summary: Python Wrapper for E-ANTIC

extra:
  recipe-maintainers:
    - saraedum
    - videlec
