# See https://github.com/conda/conda-build/issues/2666 for the missing tag
{% set version = environ.get('GIT_DESCRIBE_TAG', 'untagged')|string|replace('-','_') %}
{% set build_number = environ.get('GIT_DESCRIBE_NUMBER', '0') %}
{% set name = name or 'pyeantic' %}
{% set target = target or 'release' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}

build:
  number: {{ build_number }}
  string: {{ target }}_py{{ python }}_{{ build_number }}
  # e-antic & cppyy are not available for Windows, https://github.com/conda-forge/e-antic-feedstock/issues/6
  skip: True  # [win]
  # e-antic is not available on macOS, https://github.com/flatsurf/e-antic-feedstock/pull/3
  skip: True  # [osx]
  # we do not support old versions of Python
  skip: True  # [py<36]
  run_exports:
    # We pin exactly since we do not want to bother with incompatibilities in
    # our nightly builds.
    - {{ pin_subpackage(name, exact=True) }}

requirements:
  build:
    - libtool
    - automake
    # to search for the renfxx library, the C++ wrapper for e-antic
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    # We need all runtime dependencies to run tests during the build
    - cppyy
    - boost-cpp
    - e-antic 1.*
    # enable check-valgrind in ./configure
    - valgrind >=3.15.0  # [linux]
    # We use pytest for testing
    - pytest
    # We want to run our optional SageMath tests
    - sagelib
    - pip
    - ipywidgets
    - sympy
  run:
    - python
    - cppyy
    - boost-cpp
    # Strangely run_exports of e-antic is not picked up correctly (it's missing from the package on flatsurf)
    # This is probably due to recent bugs in conda-build (mid 2019)
    - e-antic 1.*

outputs:
  - name: {{ name }}
    script: install.sh
    test:
      imports:
        - pyeantic

about:
  home: https://github.com/flatsurf/pyeantic
  license: GPL3
  license_file: COPYING
  summary: Python Wrapper for E-ANTIC

extra:
  recipe-maintainers:
    - saraedum
    - videlec
