# We need to define the channel here and in conda_build_config.yaml, see https://github.com/conda-forge/conda-smithy/issues/996
channels:
  targets:
  - [flatsurf, main]
  sources: [flatsurf, conda-forge, defaults]
azure:
  user_or_org: flatsurf
  project_name: conda
secrets:
  - CODECOV_TOKEN
  - ASV_SECRET_KEY
channel_name: flatsurf
skip_render:
  - README.md
  - LICENSE.txt
  - .gitattributes
  - .gitignore
  - build-locally.py
  - .github/workflows/automerge.yml
  - .github/workflows/webservices.yml
